[package]
name = "benefice"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = { version = "0.9.4", features = ["std"] }
axum = { version = "0.5.5", features = ["multipart", "headers"] }
askama = { version = "0.11.1", default-features = false }
base64 = "0.13.0"
tokio = { version = "1.19.2", features = ["macros", "process", "rt-multi-thread", "io-util", "sync"] }
tracing = { version = "0.1.35", default-features = false, features = ["std", "release_max_level_info"] }
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
tower-http = { version = "0.3.0", features = ["trace"] }
uuid = { version = "*", features = ["v4"] }
once_cell = "1.12.0"
tempfile = "3.3.0"
anyhow = { version = "1.0.57", default-features = false, features = ["std"] }
reqwest = { version = "0.11.11", default-features = false, features = ["default-tls", "json"] }
clap = { version = "3.2.3", default-features = false, features = ["derive", "std"] }
openidconnect = { version = "2.3.1", default-features = false, features = ["rustls-tls", "reqwest"] }
toml = { version = "0.5.9", default-features = false }
num_cpus = "1.13.1"
rand = "0.8.5"
serde = { version = "1.0.136", default-features = false }
serde_json = { version = "1.0.82", default-features = false }
enarx-config = { version = "0.6.1", default-features = false }
zeroize = "1.5.7"

