[package]
name = "benefice"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/auth",
]

[dependencies]
axum = { version = "0.5.5", features = ["multipart"] }
tokio = { version = "1.19.2", features = ["macros", "process", "rt-multi-thread", "io-util", "sync"] }
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
tower-http = { version = "0.3.0", features = ["trace"] }
uuid = { version = "*", features = ["v4"] }
once_cell = "1.12.0"
tempfile = "3.3.0"
rsa = { version = "0.6", default-features = false }
drawbridge-auth = { path = "crates/auth" }
